categories = {
    'sport:9pin': 'sport_0',
    'sport:10pin': 'sport_1',
    'sport:american_football': 'sport_2',
    'sport:aikido': 'sport_3',
    'sport:archery': 'sport_4',
    'sport:athletics': 'sport_5',
    'sport:australian_football': 'sport_6',
    'sport:badminton': 'sport_7',
    'sport:bandy': 'sport_8',
    'sport:baseball': 'sport_9',
    'sport:basketball': 'sport_10',
    'sport:beachvolleyball': 'sport_11',
    'sport:biathlon': 'sport_12',
    'sport:billiards': 'sport_13',
    'sport:bmx': 'sport_14',
    'sport:bobsleigh': 'sport_15',
    'sport:boules': 'sport_16',
    'sport:bowls': 'sport_17',
    'sport:boxing': 'sport_18',
    'sport:bullfighting': 'sport_19',
    'sport:canadian_football': 'sport_20',
    'sport:canoe': 'sport_21',
    'sport:chess': 'sport_22',
    'sport:cliff_diving': 'sport_23',
    'sport:climbing': 'sport_24',
    'sport:climbing_adventure': 'sport_25',
    'sport:cockfighting': 'sport_26',
    'sport:cricket': 'sport_27',
    'sport:crossfit': 'sport_28',
    'sport:croquet': 'sport_29',
    'sport:curling': 'sport_30',
    'sport:cycle_polo': 'sport_31',
    'sport:cycling': 'sport_32',
    'sport:darts': 'sport_33',
    'sport:dog_agility': 'sport_34',
    'sport:dog_racing': 'sport_35',
    'sport:equestrian': 'sport_36',
    'sport:fencing': 'sport_37',
    'sport:field_hockey': 'sport_38',
    'sport:fitness': 'sport_39',
    'sport:five-a-side': 'sport_40',
    'sport:floorball': 'sport_41',
    'sport:free_flying': 'sport_42',
    'sport:futsal': 'sport_43',
    'sport:gaelic_games': 'sport_44',
    'sport:golf': 'sport_45',
    'sport:gymnastics': 'sport_46',
    'sport:handball': 'sport_47',
    'sport:hapkido': 'sport_48',
    'sport:horseshoes': 'sport_49',
    'sport:horse_racing': 'sport_50',
    'sport:ice_hockey': 'sport_51',
    'sport:ice_skating': 'sport_52',
    'sport:ice_stock': 'sport_53',
    'sport:jiu-jitsu': 'sport_54',
    'sport:judo': 'sport_55',
    'sport:karate': 'sport_56',
    'sport:karting': 'sport_57',
    'sport:kickboxing': 'sport_58',
    'sport:kitesurfing': 'sport_59',
    'sport:korfball': 'sport_60',
    'sport:krachtbal': 'sport_61',
    'sport:lacrosse': 'sport_62',
    'sport:martial_arts': 'sport_63',
    'sport:miniature_golf': 'sport_64',
    'sport:model_aerodrome': 'sport_65',
    'sport:motocross': 'sport_66',
    'sport:motor': 'sport_67',
    'sport:multi': 'sport_68',
    'sport:netball': 'sport_69',
    'sport:obstacle_course': 'sport_70',
    'sport:orienteering': 'sport_71',
    'sport:paddle_tennis': 'sport_72',
    'sport:padel': 'sport_73',
    'sport:parachuting': 'sport_74',
    'sport:parkour': 'sport_75',
    'sport:pedal_car_racing': 'sport_76',
    'sport:pelota': 'sport_77',
    'sport:pesäpallo': 'sport_78',
    'sport:pickleball': 'sport_79',
    'sport:pilates': 'sport_80',
    'sport:pole_dance': 'sport_81',
    'sport:racquet': 'sport_82',
    'sport:rc_car': 'sport_83',
    'sport:roller_skating': 'sport_84',
    'sport:rowing': 'sport_85',
    'sport:rugby_league': 'sport_86',
    'sport:rugby_union': 'sport_87',
    'sport:running': 'sport_88',
    'sport:sailing': 'sport_89',
    'sport:scuba_diving': 'sport_90',
    'sport:shooting': 'sport_91',
    'sport:shot-put': 'sport_92',
    'sport:skateboard': 'sport_93',
    'sport:ski_jumping': 'sport_94',
    'sport:skiing': 'sport_95',
    'sport:snooker': 'sport_96',
    'sport:soccer': 'sport_97',
    'sport:speedway': 'sport_98',
    'sport:squash': 'sport_99',
    'sport:sumo': 'sport_100',
    'sport:surfing': 'sport_101',
    'sport:swimming': 'sport_102',
    'sport:table_tennis': 'sport_103',
    'sport:table_soccer': 'sport_104',
    'sport:taekwondo': 'sport_105',
    'sport:tennis': 'sport_106',
    'sport:toboggan': 'sport_107',
    'sport:ultimate': 'sport_108',
    'sport:volleyball': 'sport_109',
    'sport:wakeboarding': 'sport_110',
    'sport:water_polo': 'sport_111',
    'sport:water_ski': 'sport_112',
    'sport:weightlifting': 'sport_113',
    'sport:wrestling': 'sport_114',
    'sport:yoga': 'sport_115',
    'sport:zurkhaneh_sport': 'sport_116',

    'tourism:alpine_hut': 'tourism_0',
    'tourism:apartment': 'tourism_1',
    'tourism:aquarium': 'tourism_2',
    'tourism:artwork': 'tourism_3',
    'tourism:attraction': 'tourism_4',
    'tourism:camp_pitch': 'tourism_5',
    'tourism:camp_site': 'tourism_6',
    'tourism:caravan_site': 'tourism_7',
    'tourism:chalet': 'tourism_8',
    'tourism:gallery': 'tourism_9',
    'tourism:guest_house': 'tourism_10',
    'tourism:hostel': 'tourism_11',
    'tourism:hotel': 'tourism_12',
    'tourism:information': 'tourism_13',
    'tourism:motel': 'tourism_14',
    'tourism:museum': 'tourism_15',
    'tourism:picnic_site': 'tourism_16',
    'tourism:theme_park': 'tourism_17',
    'tourism:viewpoint': 'tourism_18',
    'tourism:wilderness_hut': 'tourism_19',
    'tourism:zoo': 'tourism_20',
    'tourism:yes': 'tourism_21',

    'natural:wood': 'natural_0',
    'natural:tree_row': 'natural_1',
    'natural:tree': 'natural_2',
    'natural:scrub': 'natural_3',
    'natural:heath': 'natural_4',
    'natural:moor': 'natural_5',
    'natural:grassland': 'natural_6',
    'natural:fell': 'natural_7',
    'natural:bare_rock': 'natural_8',
    'natural:scree': 'natural_9',
    'natural:shingle': 'natural_10',
    'natural:sand': 'natural_11',
    'natural:mud': 'natural_12',

    'craft:agricultural_engines': 'craft_0',
    'craft:atelier': 'craft_1',
    'craft:bakery': 'craft_2',
    'craft:basket_maker': 'craft_3',
    'craft:beekeeper': 'craft_4',
    'craft:blacksmith': 'craft_5',
    'craft:boatbuilder': 'craft_6',
    'craft:bookbinder': 'craft_7',
    'craft:brewery': 'craft_8',
    'craft:builder': 'craft_9',
    'craft:cabinet_maker': 'craft_10',
    'craft:car_painter': 'craft_11',
    'craft:carpenter': 'craft_12',
    'craft:carpet_layer': 'craft_13',
    'craft:caterer': 'craft_14',
    'craft:chimney_sweeper': 'craft_15',
    'craft:cleaning': 'craft_16',
    'craft:clockmaker': 'craft_17',
    'craft:confectionery': 'craft_18',
    'craft:cooper': 'craft_19',
    'craft:dental_technician': 'craft_20',
    'craft:distillery': 'craft_21',
    'craft:door_construction': 'craft_22',
    'craft:dressmaker': 'craft_23',
    'craft:electronics_repair': 'craft_24',
    'craft:embroiderer': 'craft_25',
    'craft:electrician': 'craft_26',
    'craft:engraver': 'craft_27',
    'craft:floorer': 'craft_28',
    'craft:gardener': 'craft_29',
    'craft:glaziery': 'craft_30',
    'craft:goldsmith': 'craft_31',
    'craft:grinding_mill': 'craft_32',
    'craft:handicraft': 'craft_33',
    'craft:hvac': 'craft_34',
    'craft:insulation': 'craft_35',
    'craft:interior_work': 'craft_36',
    'craft:jeweller': 'craft_37',
    'craft:joiner': 'craft_38',
    'craft:key_cutter': 'craft_39',
    'craft:locksmith': 'craft_40',
    'craft:metal_construction': 'craft_41',
    'craft:mint': 'craft_42',
    'craft:musical_instrument': 'craft_43',
    'craft:oil_mill': 'craft_44',
    'craft:optician': 'craft_45',
    'craft:organ_builder': 'craft_46',
    'craft:painter': 'craft_47',
    'craft:parquet_layer': 'craft_48',
    'craft:paver': 'craft_49',
    'craft:photographer': 'craft_50',
    'craft:photographic_laboratory': 'craft_51',
    'craft:piano_tuner': 'craft_52',
    'craft:plasterer': 'craft_53',
    'craft:plumber': 'craft_54',
    'craft:pottery': 'craft_55',
    'craft:printer': 'craft_56',
    'craft:printmaker': 'craft_57',
    'craft:rigger': 'craft_58',
    'craft:roofer': 'craft_59',
    'craft:saddler': 'craft_60',
    'craft:sailmaker': 'craft_61',
    'craft:sawmill': 'craft_62',
    'craft:scaffolder': 'craft_63',
    'craft:sculptor': 'craft_64',
    'craft:shoemaker': 'craft_65',
    'craft:signmaker': 'craft_66',
    'craft:stand_builder': 'craft_67',
    'craft:stonemason': 'craft_68',
    'craft:stove_fitter': 'craft_69',
    'craft:sun_protection': 'craft_70',
    'craft:tailor': 'craft_71',
    'craft:tiler': 'craft_72',
    'craft:tinsmith': 'craft_73',
    'craft:toolmaker': 'craft_74',
    'craft:turner': 'craft_75',
    'craft:upholsterer': 'craft_76',
    'craft:watchmaker': 'craft_77',
    'craft:water_well_drilling': 'craft_78',
    'craft:window_construction': 'craft_79',
    'craft:winery': 'craft_80',

    'barrier:cable_barrier': 'barrier_0',
    'barrier:city_wall': 'barrier_1',
    'barrier:ditch': 'barrier_2',
    'barrier:fence': 'barrier_3',
    'barrier:guard_rail': 'barrier_4',
    'barrier:handrail': 'barrier_5',
    'barrier:hedge': 'barrier_6',
    'barrier:kerb': 'barrier_7',
    'barrier:retaining_wall': 'barrier_8',
    'barrier:wall': 'barrier_9',
    'barrier:block': 'barrier_10',
    'barrier:bollard': 'barrier_11',
    'barrier:border_control': 'barrier_12',
    'barrier:bump_gate': 'barrier_13',
    'barrier:bus_trap': 'barrier_14',
    'barrier:cattle_grid': 'barrier_15',
    'barrier:chain': 'barrier_16',
    'barrier:cycle_barrier': 'barrier_17',
    'barrier:debris': 'barrier_18',
    'barrier:entrance': 'barrier_19',
    'barrier:full': 'barrier_20',
    'barrier:gate': 'barrier_21',
    'barrier:hampshire_gate': 'barrier_22',
    'barrier:height_restrictor': 'barrier_23',
    'barrier:horse_stile': 'barrier_24',
    'barrier:jersey_barrier': 'barrier_25',
    'barrier:kissing_gate': 'barrier_26',
    'barrier:lift_gate': 'barrier_27',
    'barrier:log': 'barrier_28',
    'barrier:motorcycle_barrier': 'barrier_29',
    'barrier:rope': 'barrier_30',
    'barrier:sally_port': 'barrier_31',
    'barrier:spikes': 'barrier_32',
    'barrier:stile': 'barrier_33',
    'barrier:sump_buster': 'barrier_34',
    'barrier:swing_gate': 'barrier_35',
    'barrier:toll_booth': 'barrier_36',
    'barrier:turnstile': 'barrier_37',
    'barrier:yes': 'barrier_38',

    'shop:alcohol': 'shop_0',
    'shop:bakery': 'shop_1',
    'shop:beverages': 'shop_2',
    'shop:brewing_supplies': 'shop_3',
    'shop:butcher': 'shop_4',
    'shop:cheese': 'shop_5',
    'shop:chocolate': 'shop_6',
    'shop:coffee': 'shop_7',
    'shop:confectionery': 'shop_8',
    'shop:convenience': 'shop_9',
    'shop:deli': 'shop_10',
    'shop:dairy': 'shop_11',
    'shop:farm': 'shop_12',
    'shop:frozen_food': 'shop_13',
    'shop:greengrocer': 'shop_14',
    'shop:health_food': 'shop_15',
    'shop:ice_cream': 'shop_16',
    'shop:organic': 'shop_17',
    'shop:pasta': 'shop_18',
    'shop:pastry': 'shop_19',
    'shop:seafood': 'shop_20',
    'shop:spices': 'shop_21',
    'shop:tea': 'shop_22',
    'shop:wine': 'shop_23',
    'shop:water': 'shop_24',
    'shop:department_store': 'shop_25',
    'shop:general': 'shop_26',
    'shop:kiosk': 'shop_27',
    'shop:mall': 'shop_28',
    'shop:supermarket': 'shop_29',
    'shop:wholesale': 'shop_30',
    'shop:baby_goods': 'shop_31',
    'shop:bag': 'shop_32',
    'shop:boutique': 'shop_33',
    'shop:clothes': 'shop_34',
    'shop:fabric': 'shop_35',
    'shop:fashion': 'shop_36',
    'shop:fashion_accessories': 'shop_37',
    'shop:jewelry': 'shop_38',
    'shop:leather': 'shop_39',
    'shop:sewing': 'shop_40',
    'shop:shoes': 'shop_41',
    'shop:tailor': 'shop_42',
    'shop:watches': 'shop_43',
    'shop:wool': 'shop_44',
    'shop:charity': 'shop_45',
    'shop:second_hand': 'shop_46',
    'shop:variety_store': 'shop_47',
    'shop:beauty': 'shop_48',
    'shop:chemist': 'shop_49',
    'shop:cosmetics': 'shop_50',
    'shop:drugstore': 'shop_51',
    'shop:erotic': 'shop_52',
    'shop:hairdresser': 'shop_53',
    'shop:hairdresser_supply': 'shop_54',
    'shop:hearing_aids': 'shop_55',
    'shop:herbalist': 'shop_56',
    'shop:massage': 'shop_57',
    'shop:medical_supply': 'shop_58',
    'shop:nutrition_supplements': 'shop_59',
    'shop:optician': 'shop_60',
    'shop:perfumery': 'shop_61',
    'shop:tattoo': 'shop_62',
    'shop:agrarian': 'shop_63',
    'shop:appliance': 'shop_64',
    'shop:bathroom_furnishing': 'shop_65',
    'shop:doityourself': 'shop_66',
    'shop:electrical': 'shop_67',
    'shop:energy': 'shop_68',
    'shop:fireplace': 'shop_69',
    'shop:florist': 'shop_70',
    'shop:garden_centre': 'shop_71',
    'shop:garden_furniture': 'shop_72',
    'shop:gas': 'shop_73',
    'shop:glaziery': 'shop_74',
    'shop:groundskeeping': 'shop_75',
    'shop:hardware': 'shop_76',
    'shop:houseware': 'shop_77',
    'shop:locksmith': 'shop_78',
    'shop:paint': 'shop_79',
    'shop:security': 'shop_80',
    'shop:trade': 'shop_81',
    'shop:windows': 'shop_82',
    'shop:antiques': 'shop_83',
    'shop:bed': 'shop_84',
    'shop:candles': 'shop_85',
    'shop:carpet': 'shop_86',
    'shop:curtain': 'shop_87',
    'shop:doors': 'shop_88',
    'shop:flooring': 'shop_89',
    'shop:furniture': 'shop_90',
    'shop:household_linen': 'shop_91',
    'shop:interior_decoration': 'shop_92',
    'shop:kitchen': 'shop_93',
    'shop:lamps': 'shop_94',
    'shop:lighting': 'shop_95',
    'shop:tiles': 'shop_96',
    'shop:window_blind': 'shop_97',
    'shop:computer': 'shop_98',
    'shop:electronics': 'shop_99',
    'shop:hifi': 'shop_100',
    'shop:mobile_phone': 'shop_101',
    'shop:radiotechnics': 'shop_102',
    'shop:vacuum_cleaner': 'shop_103',
    'shop:atv': 'shop_104',
    'shop:bicycle': 'shop_105',
    'shop:boat': 'shop_106',
    'shop:car': 'shop_107',
    'shop:car_repair': 'shop_108',
    'shop:car_parts': 'shop_109',
    'shop:caravan': 'shop_110',
    'shop:fuel': 'shop_111',
    'shop:fishing': 'shop_112',
    'shop:golf': 'shop_113',
    'shop:hunting': 'shop_114',
    'shop:jetski': 'shop_115',
    'shop:military_surplus': 'shop_116',
    'shop:motorcycle': 'shop_117',
    'shop:outdoor': 'shop_118',
    'shop:scuba_diving': 'shop_119',
    'shop:ski': 'shop_120',
    'shop:snowmobile': 'shop_121',
    'shop:sports': 'shop_122',
    'shop:swimming_pool': 'shop_123',
    'shop:trailer': 'shop_124',
    'shop:tyres': 'shop_125',
    'shop:art': 'shop_126',
    'shop:collector': 'shop_127',
    'shop:craft': 'shop_128',
    'shop:frame': 'shop_129',
    'shop:games': 'shop_130',
    'shop:model': 'shop_131',
    'shop:music': 'shop_132',
    'shop:musical_instrument': 'shop_133',
    'shop:photo': 'shop_134',
    'shop:camera': 'shop_135',
    'shop:trophy': 'shop_136',
    'shop:video': 'shop_137',
    'shop:video_games': 'shop_138',
    'shop:anime': 'shop_139',
    'shop:books': 'shop_140',
    'shop:gift': 'shop_141',
    'shop:lottery': 'shop_142',
    'shop:newsagent': 'shop_143',
    'shop:stationery': 'shop_144',
    'shop:ticket': 'shop_145',
    'shop:bookmaker': 'shop_146',
    'shop:cannabis': 'shop_147',
    'shop:copyshop': 'shop_148',
    'shop:dry_cleaning': 'shop_149',
    'shop:e-cigarette': 'shop_150',
    'shop:funeral_directors': 'shop_151',
    'shop:laundry': 'shop_152',
    'shop:money_lender': 'shop_153',
    'shop:party': 'shop_154',
    'shop:pawnbroker': 'shop_155',
    'shop:pet': 'shop_156',
    'shop:pet_grooming': 'shop_157',
    'shop:pest_control': 'shop_158',
    'shop:pyrotechnics': 'shop_159',
    'shop:religion': 'shop_160',
    'shop:storage_rental': 'shop_161',
    'shop:tobacco': 'shop_162',
    'shop:toys': 'shop_163',
    'shop:travel_agency': 'shop_164',
    'shop:vacant': 'shop_165',
    'shop:weapons': 'shop_166',
    'shop:outpost': 'shop_167',
    'shop:user defined': 'shop_168',

    'railway:abandoned': 'railway_0',
    'railway:construction': 'railway_1',
    'railway:disused': 'railway_2',
    'railway:funicular': 'railway_3',
    'railway:light_rail': 'railway_4',
    'railway:miniature': 'railway_5',
    'railway:monorail': 'railway_6',
    'railway:narrow_gauge': 'railway_7',
    'railway:preserved': 'railway_8',
    'railway:rail': 'railway_9',
    'railway:subway': 'railway_10',
    'railway:tram': 'railway_11',
    'railway:halt': 'railway_12',
    'railway:stop_position': 'railway_13',
    'railway:platform': 'railway_14',
    'railway:station': 'railway_15',
    'railway:subway_entrance': 'railway_16',
    'railway:tram_stop': 'railway_17',
    'railway:buffer_stop': 'railway_18',
    'railway:derail': 'railway_19',
    'railway:crossing': 'railway_20',
    'railway:level_crossing': 'railway_21',
    'railway:signal': 'railway_22',
    'railway:switch': 'railway_23',
    'railway:railway_crossing': 'railway_24',
    'railway:turntable': 'railway_25',
    'railway:roundhouse': 'railway_26',
    'railway:traverser': 'railway_27',
    'railway:wash': 'railway_28',
    'railway:user defined': 'railway_29',

    'public_transportation:stop_position': 'public_transportation_0',
    'public_transportation:platform': 'public_transportation_1',
    'public_transportation:station': 'public_transportation_2',

    'highway:milestone': 'highway_0',
    'highway:mini_roundabout': 'highway_1',
    'highway:motorway_junction': 'highway_2',
    'highway:passing_place': 'highway_3',
    'highway:platform': 'highway_4',
    'highway:rest_area': 'highway_5',
    'highway:speed_camera': 'highway_6',
    'highway:street_lamp': 'highway_7',
    'highway:services': 'highway_8',
    'highway:stop': 'highway_9',
    'highway:traffic_mirror': 'highway_10',
    'highway:traffic_signals': 'highway_11',
    'highway:trailhead': 'highway_12',
    'highway:turning_circle': 'highway_13',
    'highway:turning_loop': 'highway_14',
    'highway:toll_gantry': 'highway_15',
    'highway:bus_stop': 'highway_16',
    'highway:crossing': 'highway_17',
    'highway:elevator': 'highway_18',
    'highway:emergency_bay': 'highway_19',
    'highway:emergency_access_point': 'highway_20',
    'highway:give_way': 'highway_21',
    'highway:motorway': 'highway_22',
    'highway:trunk': 'highway_23',
    'highway:primary': 'highway_24',
    'highway:secondary': 'highway_25',
    'highway:tertiary': 'highway_26',
    'highway:unclassified': 'highway_27',
    'highway:residential': 'highway_28',
    'highway:motorway_link': 'highway_29',
    'highway:trunk_link': 'highway_30',
    'highway:primary_link': 'highway_31',
    'highway:secondary_link': 'highway_32',
    'highway:tertiary_link': 'highway_33',
    'highway:living_street': 'highway_34',
    'highway:service': 'highway_35',
    'highway:pedestrian': 'highway_36',
    'highway:track': 'highway_37',
    'highway:bus_guideway': 'highway_38',
    'highway:escape': 'highway_39',
    'highway:raceway': 'highway_40',
    'highway:road': 'highway_41',
    'highway:busway': 'highway_42',
    'highway:footway': 'highway_43',
    'highway:bridleway': 'highway_44',
    'highway:steps': 'highway_45',
    'highway:corridor': 'highway_46',
    'highway:path': 'highway_47',

    'footway:sidewalk': 'footway_0',
    'footway:crossing': 'footway_1',

    'cycleway:lane': 'cycleway_0',
    'cycleway:opposite': 'cycleway_1',
    'cycleway:opposite_lane': 'cycleway_2',
    'cycleway:track': 'cycleway_3',
    'cycleway:opposite_track': 'cycleway_4',
    'cycleway:share_busway': 'cycleway_5',
    'cycleway:opposite_share_busway': 'cycleway_6',
    'cycleway:shared_lane': 'cycleway_7',

    'building:grandstand': 'building_0',
    'building:pavilion': 'building_1',
    'building:riding_hall': 'building_2',
    'building:sports_hall': 'building_3',
    'building:stadium': 'building_4',
    'building:hangar': 'building_5',
    'building:hut': 'building_6',
    'building:shed': 'building_7',
    'building:carport': 'building_8',
    'building:garage': 'building_9',
    'building:garages': 'building_10',
    'building:parking': 'building_11',
    'building:digester': 'building_12',
    'building:service': 'building_13',
    'building:transformer_tower': 'building_14',
    'building:water_tower': 'building_15',
    'building:military': 'building_16',
    'building:bunker': 'building_17',
    'building:bridge': 'building_18',
    'building:construction': 'building_19',
    'building:container': 'building_20',
    'building:tent': 'building_21',
    'building:gatehouse': 'building_22',
    'building:roof': 'building_23',
    'building:ruins': 'building_24',
    'building:tree_house': 'building_25',
    'building:yes': 'building_26',
    'building:apartments': 'building_27',
    'building:bungalow': 'building_28',
    'building:cabin': 'building_29',
    'building:detached': 'building_30',
    'building:dormitory': 'building_31',
    'building:farm': 'building_32',
    'building:ger': 'building_33',
    'building:hotel': 'building_34',
    'building:house': 'building_35',
    'building:houseboat': 'building_36',
    'building:residential': 'building_37',
    'building:semidetached_house': 'building_38',
    'building:static_caravan': 'building_39',
    'building:terrace': 'building_40',
    'building:commercial': 'building_41',
    'building:industrial': 'building_42',
    'building:kiosk': 'building_43',
    'building:office': 'building_44',
    'building:retail': 'building_45',
    'building:supermarket': 'building_46',
    'building:warehouse': 'building_47',
    'building:cathedral': 'building_48',
    'building:chapel': 'building_49',
    'building:church': 'building_50',
    'building:monastery': 'building_51',
    'building:mosque': 'building_52',
    'building:presbytery': 'building_53',
    'building:religious': 'building_54',
    'building:shrine': 'building_55',
    'building:synagogue': 'building_56',
    'building:temple': 'building_57',
    'building:bakehouse': 'building_58',
    'building:civic': 'building_59',
    'building:fire_station': 'building_60',
    'building:government': 'building_61',
    'building:hospital': 'building_62',
    'building:public': 'building_63',
    'building:toilets': 'building_64',
    'building:train_station': 'building_65',
    'building:transportation': 'building_66',
    'building:kindergarten': 'building_67',
    'building:school': 'building_68',
    'building:university': 'building_69',
    'building:college': 'building_70',
    'building:barn': 'building_71',
    'building:conservatory': 'building_72',
    'building:cowshed': 'building_73',
    'building:farm_auxiliary': 'building_74',
    'building:greenhouse': 'building_75',
    'building:slurry_tank': 'building_76',
    'building:stable': 'building_77',
    'building:sty': 'building_78',

    'amenity:bar': 'amenity_0',
    'amenity:biergarten': 'amenity_1',
    'amenity:cafe': 'amenity_2',
    'amenity:fast_food': 'amenity_3',
    'amenity:food_court': 'amenity_4',
    'amenity:ice_cream': 'amenity_5',
    'amenity:pub': 'amenity_6',
    'amenity:restaurant': 'amenity_7',
    'amenity:college': 'amenity_8',
    'amenity:driving_school': 'amenity_9',
    'amenity:kindergarten': 'amenity_10',
    'amenity:language_school': 'amenity_11',
    'amenity:library': 'amenity_12',
    'amenity:toy_library': 'amenity_13',
    'amenity:music_school': 'amenity_14',
    'amenity:school': 'amenity_15',
    'amenity:university': 'amenity_16',
    'amenity:bicycle_parking': 'amenity_17',
    'amenity:bicycle_repair_station': 'amenity_18',
    'amenity:bicycle_rental': 'amenity_19',
    'amenity:boat_rental': 'amenity_20',
    'amenity:boat_sharing': 'amenity_21',
    'amenity:bus_station': 'amenity_22',
    'amenity:car_rental': 'amenity_23',
    'amenity:car_sharing': 'amenity_24',
    'amenity:car_wash': 'amenity_25',
    'amenity:vehicle_inspection': 'amenity_26',
    'amenity:charging_station': 'amenity_27',
    'amenity:ferry_terminal': 'amenity_28',
    'amenity:fuel': 'amenity_29',
    'amenity:grit_bin': 'amenity_30',
    'amenity:motorcycle_parking': 'amenity_31',
    'amenity:parking': 'amenity_32',
    'amenity:parking_entrance': 'amenity_33',
    'amenity:parking_space': 'amenity_34',
    'amenity:taxi': 'amenity_35',
    'amenity:atm': 'amenity_36',
    'amenity:bank': 'amenity_37',
    'amenity:bureau_de_change': 'amenity_38',
    'amenity:baby_hatch': 'amenity_39',
    'amenity:clinic': 'amenity_40',
    'amenity:dentist': 'amenity_41',
    'amenity:doctors': 'amenity_42',
    'amenity:hospital': 'amenity_43',
    'amenity:nursing_home': 'amenity_44',
    'amenity:pharmacy': 'amenity_45',
    'amenity:social_facility': 'amenity_46',
    'amenity:veterinary': 'amenity_47',
    'amenity:arts_centre': 'amenity_48',
    'amenity:brothel': 'amenity_49',
    'amenity:casino': 'amenity_50',
    'amenity:cinema': 'amenity_51',
    'amenity:community_centre': 'amenity_52',
    'amenity:conference_centre': 'amenity_53',
    'amenity:events_venue': 'amenity_54',
    'amenity:fountain': 'amenity_55',
    'amenity:gambling': 'amenity_56',
    'amenity:love_hotel': 'amenity_57',
    'amenity:nightclub': 'amenity_58',
    'amenity:planetarium': 'amenity_59',
    'amenity:public_bookcase': 'amenity_60',
    'amenity:social_centre': 'amenity_61',
    'amenity:stripclub': 'amenity_62',
    'amenity:studio': 'amenity_63',
    'amenity:swingerclub': 'amenity_64',
    'amenity:theatre': 'amenity_65',
    'amenity:courthouse': 'amenity_66',
    'amenity:embassy': 'amenity_67',
    'amenity:fire_station': 'amenity_68',
    'amenity:police': 'amenity_69',
    'amenity:post_box': 'amenity_70',
    'amenity:post_depot': 'amenity_71',
    'amenity:post_office': 'amenity_72',
    'amenity:prison': 'amenity_73',
    'amenity:ranger_station': 'amenity_74',
    'amenity:townhall': 'amenity_75',
    'amenity:bbq': 'amenity_76',
    'amenity:bench': 'amenity_77',
    'amenity:dog_toilet': 'amenity_78',
    'amenity:drinking_water': 'amenity_79',
    'amenity:give_box': 'amenity_80',
    'amenity:shelter': 'amenity_81',
    'amenity:shower': 'amenity_82',
    'amenity:telephone': 'amenity_83',
    'amenity:toilets': 'amenity_84',
    'amenity:water_point': 'amenity_85',
    'amenity:watering_place': 'amenity_86',
    'amenity:sanitary_dump_station': 'amenity_87',
    'amenity:recycling': 'amenity_88',
    'amenity:waste_basket': 'amenity_89',
    'amenity:waste_disposal': 'amenity_90',
    'amenity:waste_transfer_station': 'amenity_91',
    'amenity:animal_boarding': 'amenity_92',
    'amenity:animal_breeding': 'amenity_93',
    'amenity:animal_shelter': 'amenity_94',
    'amenity:baking_oven': 'amenity_95',
    'amenity:childcare': 'amenity_96',
    'amenity:clock': 'amenity_97',
    'amenity:crematorium': 'amenity_98',
    'amenity:dive_centre': 'amenity_99',
    'amenity:funeral_hall': 'amenity_100',
    'amenity:grave_yard': 'amenity_101',
    'amenity:gym': 'amenity_102',
    'amenity:hunting_stand': 'amenity_103',
    'amenity:internet_cafe': 'amenity_104',
    'amenity:kitchen': 'amenity_105',
    'amenity:kneipp_water_cure': 'amenity_106',
    'amenity:lounger': 'amenity_107',
    'amenity:marketplace': 'amenity_108',
    'amenity:monastery': 'amenity_109',
    'amenity:photo_booth': 'amenity_110',
    'amenity:place_of_mourning': 'amenity_111',
    'amenity:place_of_worship': 'amenity_112',
    'amenity:public_bath': 'amenity_113',
    'amenity:public_building': 'amenity_114',
    'amenity:refugee_site': 'amenity_115',
    'amenity:vending_machine': 'amenity_116',
    'amenity:user defined': 'amenity_117',
}

ontology = {
    'places': {
        'sports': [
            'amenity:gym',
            'leisure:sports_centre',
            'leisure:stadium',
            'building:grandstand',
            'building:pavilion',
            'building:riding_hall',
            'building:sports_hall',
            'building:stadium',
            'sport:9pin',
            'sport:10pin',
            'sport:american_football',
            'sport:aikido',
            'sport:archery',
            'sport:athletics',
            'sport:australian_football',
            'sport:badminton',
            'sport:bandy',
            'sport:baseball',
            'sport:basketball',
            'sport:beachvolleyball',
            'sport:biathlon',
            'sport:billiards',
            'sport:bmx',
            'sport:bobsleigh',
            'sport:boules',
            'sport:bowls',
            'sport:boxing',
            'sport:bullfighting',
            'sport:canadian_football',
            'sport:canoe',
            'sport:chess',
            'sport:cliff_diving',
            'sport:climbing',
            'sport:climbing_adventure',
            'sport:cockfighting',
            'sport:cricket',
            'sport:crossfit',
            'sport:croquet',
            'sport:curling',
            'sport:cycle_polo',
            'sport:cycling',
            'sport:darts',
            'sport:dog_agility',
            'sport:dog_racing',
            'sport:equestrian',
            'sport:fencing',
            'sport:field_hockey',
            'sport:fitness',
            'sport:five-a-side',
            'sport:floorball',
            'sport:free_flying',
            'sport:futsal',
            'sport:gaelic_games',
            'sport:golf',
            'sport:gymnastics',
            'sport:handball',
            'sport:hapkido',
            'sport:horseshoes',
            'sport:horse_racing',
            'sport:ice_hockey',
            'sport:ice_skating',
            'sport:ice_stock',
            'sport:jiu-jitsu',
            'sport:judo',
            'sport:karate',
            'sport:karting',
            'sport:kickboxing',
            'sport:kitesurfing',
            'sport:korfball',
            'sport:krachtbal',
            'sport:lacrosse',
            'sport:martial_arts',
            'sport:miniature_golf',
            'sport:model_aerodrome',
            'sport:motocross',
            'sport:motor',
            'sport:multi',
            'sport:netball',
            'sport:obstacle_course',
            'sport:orienteering',
            'sport:paddle_tennis',
            'sport:padel',
            'sport:parachuting',
            'sport:parkour',
            'sport:pedal_car_racing',
            'sport:pelota',
            'sport:pesäpallo',
            'sport:pickleball',
            'sport:pilates',
            'sport:pole_dance',
            'sport:racquet',
            'sport:rc_car',
            'sport:roller_skating',
            'sport:rowing',
            'sport:rugby_league',
            'sport:rugby_union',
            'sport:running',
            'sport:sailing',
            'sport:scuba_diving',
            'sport:shooting',
            'sport:shot-put',
            'sport:skateboard',
            'sport:ski_jumping',
            'sport:skiing',
            'sport:snooker',
            'sport:soccer',
            'sport:speedway',
            'sport:squash',
            'sport:sumo',
            'sport:surfing',
            'sport:swimming',
            'sport:table_tennis',
            'sport:table_soccer',
            'sport:taekwondo',
            'sport:tennis',
            'sport:toboggan',
            'sport:ultimate',
            'sport:volleyball',
            'sport:wakeboarding',
            'sport:water_polo',
            'sport:water_ski',
            'sport:weightlifting',
            'sport:wrestling',
            'sport:yoga',
            'sport:zurkhaneh_sport',
        ],
        'school': {
            '0': [
                'amenity:kindergarten',
                'building:kindergarten',
                'amenity:childcare',
            ],
            '1': [
                'amenity:school',
                'building:school',
            ],
            '2': [
                'amenity:university',
                'amenity:college',
                'building:university',
                'building:college',
            ],
            'other': [
                'amenity:driving_school',
                'amenity:language_school',
                'amenity:music_school',
            ],
        },
        'health': [
            'amenity:clinic',
            'amenity:dentist',
            'amenity:doctors',
            'amenity:hospital',
            'building:hospital',
            'amenity:pharmacy',
            'shop:chemist',
            'shop:drugstore',
            'shop:medical_supply',
            'shop:nutrition_supplements',
            'shop:optician',
        ],
        'religious': [
            'amenity:place_of_mourning',
            'amenity:place_of_worship',
            'amenity:monastery',
            'building:cathedral',
            'building:chapel',
            'building:church',
            'building:monastery',
            'building:mosque',
            'building:presbytery',
            'building:religious',
            'building:shrine',
            'building:synagogue',
            'building:temple',
        ],
        'bank': [
            'amenity:bank',
            'amenity:atm',
        ],
        'food_drink': [
            'amenity:fast_food',
            'amenity:food_court',
            'amenity:ice_cream',
            'amenity:restaurant',
            'amenity:kitchen',
            'amenity:bar',
            'amenity:biergarten',
            'amenity:cafe',
            'amenity:pub',
        ],
        'amenity': [
            'amenity:toy_library',
            'amenity:bureau_de_change',
            'amenity:baby_hatch',
            'amenity:social_facility',
            'amenity:veterinary',
            'amenity:brothel',
            'amenity:conference_centre',
            'amenity:events_venue',
            'amenity:gambling',
            'amenity:planetarium',
            'amenity:public_bookcase',
            'amenity:social_centre',
            'amenity:nursing_home',
            'amenity:stripclub',
            'amenity:studio',
            'amenity:swingerclub',
            'amenity:post_depot',
            'amenity:prison',
            'amenity:ranger_station',
            'amenity:give_box',
            'amenity:shelter',
            'amenity:shower',
            'amenity:sanitary_dump_station',
            'amenity:waste_disposal',
            'amenity:waste_transfer_station',
            'amenity:animal_boarding',
            'amenity:animal_breeding',
            'amenity:animal_shelter',
            'amenity:baking_oven',
            'amenity:crematorium',
            'amenity:dive_centre',
            'amenity:funeral_hall',
            'amenity:grave_yard',
            'amenity:hunting_stand',
            'amenity:kneipp_water_cure',
            'amenity:lounger',
            'amenity:photo_booth',
            'amenity:public_bath',
            'amenity:refugee_site',
            'amenity:user defined',
        ],
        'shop': {
            'general': [
                'building:supermarket',
                'shop:convenience',
                'shop:deli',
                'shop:supermarket',
                'shop:general',
                'shop:wholesale',
                'building:retail',
                'amenity:marketplace',
            ],
            'big':[
                'shop:department_store',
                'shop:mall',
            ],
            'specialty': {
                    'food_drinks': [
                        'shop:alcohol',
                        'shop:bakery',
                        'shop:beverages',
                        'shop:butcher',
                        'shop:cheese',
                        'shop:chocolate',
                        'shop:coffee',
                        'shop:confectionery',
                        'shop:dairy',
                        'shop:frozen_food',
                        'shop:greengrocer',
                        'shop:health_food',
                        'shop:ice_cream',
                        'shop:organic',
                        'shop:pasta',
                        'shop:pastry',
                        'shop:seafood',
                        'shop:spices',
                        'shop:tea',
                        'shop:wine',
                        'shop:water',
                        'craft:bakery', # A bakery is a shop selling bread.
                        'craft:winery',
                    ],
                    'transportation': [
                        'shop:tyres',
                        'shop:atv',
                        'shop:bicycle',
                        'shop:boat',
                        'shop:car',
                        'shop:car_repair',
                        'shop:car_parts',
                        'shop:caravan',
                        'shop:trailer',
                        'shop:motorcycle',
                        'shop:snowmobile',
                        'amenity:bicycle_rental',
                        'amenity:boat_rental',
                        'amenity:boat_sharing',
                        'amenity:car_rental',
                        'amenity:car_wash',
                        'amenity:vehicle_inspection',
                        'amenity:ferry_terminal',
                    ],
                    'other': [
                        'shop:brewing_supplies',
                        'shop:farm',
                        'shop:kiosk',
                        'shop:baby_goods',
                        'shop:bag',
                        'shop:boutique',
                        'shop:clothes',
                        'shop:fabric',
                        'shop:fashion',
                        'shop:fashion_accessories',
                        'shop:jewelry',
                        'shop:leather',
                        'shop:sewing',
                        'shop:shoes',
                        'shop:tailor',
                        'shop:watches',
                        'shop:wool',
                        'shop:charity',
                        'shop:second_hand',
                        'shop:variety_store',
                        'shop:beauty',
                        'shop:cosmetics',
                        'shop:erotic',
                        'shop:hairdresser',
                        'shop:hairdresser_supply',
                        'shop:hearing_aids',
                        'shop:herbalist',
                        'shop:massage',
                        'shop:perfumery',
                        'shop:tattoo',
                        'shop:agrarian',
                        'shop:appliance',
                        'shop:bathroom_furnishing',
                        'shop:doityourself',
                        'shop:electrical',
                        'shop:energy',
                        'shop:fireplace',
                        'shop:florist',
                        'shop:garden_centre',
                        'shop:garden_furniture',
                        'shop:gas',
                        'shop:glaziery',
                        'shop:groundskeeping',
                        'shop:hardware',
                        'shop:houseware',
                        'shop:locksmith',
                        'shop:paint',
                        'shop:security',
                        'shop:trade',
                        'shop:windows',
                        'shop:antiques',
                        'shop:bed',
                        'shop:candles',
                        'shop:carpet',
                        'shop:curtain',
                        'shop:doors',
                        'shop:flooring',
                        'shop:furniture',
                        'shop:household_linen',
                        'shop:interior_decoration',
                        'shop:kitchen',
                        'shop:lamps',
                        'shop:lighting',
                        'shop:tiles',
                        'shop:window_blind',
                        'shop:computer',
                        'shop:electronics',
                        'shop:hifi',
                        'shop:mobile_phone',
                        'shop:radiotechnics',
                        'shop:vacuum_cleaner',
                        'shop:fuel',
                        'shop:fishing',
                        'shop:golf',
                        'shop:hunting',
                        'shop:jetski',
                        'shop:military_surplus',
                        'shop:outdoor',
                        'shop:scuba_diving',
                        'shop:ski',
                        'shop:sports',
                        'shop:swimming_pool',
                        'shop:art',
                        'shop:collector',
                        'shop:craft',
                        'shop:frame',
                        'shop:games',
                        'shop:model',
                        'shop:music',
                        'shop:musical_instrument',
                        'shop:photo',
                        'shop:camera',
                        'shop:trophy',
                        'shop:video',
                        'shop:video_games',
                        'shop:anime',
                        'shop:books',
                        'shop:gift',
                        'shop:lottery',
                        'shop:newsagent',
                        'shop:stationery',
                        'shop:ticket',
                        'shop:bookmaker',
                        'shop:cannabis',
                        'shop:copyshop',
                        'shop:dry_cleaning',
                        'shop:e-cigarette',
                        'shop:funeral_directors',
                        'shop:laundry',
                        'shop:money_lender',
                        'shop:party',
                        'shop:pawnbroker',
                        'shop:pet',
                        'shop:pet_grooming',
                        'shop:pest_control',
                        'shop:pyrotechnics',
                        'shop:religion',
                        'shop:storage_rental',
                        'shop:tobacco',
                        'shop:toys',
                        'shop:travel_agency',
                        'shop:vacant',
                        'shop:weapons',
                        'shop:outpost',
                        'shop:user defined',
                        'craft:agricultural_engines',
                        'craft:atelier',
                        'craft:basket_maker',
                        'craft:beekeeper',
                        'craft:blacksmith',
                        'craft:boatbuilder',
                        'craft:bookbinder',
                        'craft:brewery',
                        'craft:builder',
                        'craft:cabinet_maker',
                        'craft:car_painter',
                        'craft:carpenter',
                        'craft:carpet_layer',
                        'craft:caterer',
                        'craft:chimney_sweeper',
                        'craft:cleaning',
                        'craft:clockmaker',
                        'craft:confectionery',
                        'craft:cooper',
                        'craft:dental_technician',
                        'craft:distillery',
                        'craft:door_construction',
                        'craft:dressmaker',
                        'craft:electronics_repair',
                        'craft:embroiderer',
                        'craft:electrician',
                        'craft:engraver',
                        'craft:floorer',
                        'craft:gardener',
                        'craft:glaziery',
                        'craft:goldsmith',
                        'craft:grinding_mill',
                        'craft:handicraft',
                        'craft:hvac',
                        'craft:insulation',
                        'craft:interior_work',
                        'craft:jeweller',
                        'craft:joiner',
                        'craft:key_cutter',
                        'craft:locksmith',
                        'craft:metal_construction',
                        'craft:mint',
                        'craft:musical_instrument',
                        'craft:oil_mill',
                        'craft:optician',
                        'craft:organ_builder',
                        'craft:painter',
                        'craft:parquet_layer',
                        'craft:paver',
                        'craft:photographer',
                        'craft:photographic_laboratory',
                        'craft:piano_tuner',
                        'craft:plasterer',
                        'craft:plumber',
                        'craft:pottery',
                        'craft:printer',
                        'craft:printmaker',
                        'craft:rigger',
                        'craft:roofer',
                        'craft:saddler',
                        'craft:sailmaker',
                        'craft:sawmill',
                        'craft:scaffolder',
                        'craft:sculptor',
                        'craft:shoemaker',
                        'craft:signmaker',
                        'craft:stand_builder',
                        'craft:stonemason',
                        'craft:stove_fitter',
                        'craft:sun_protection',
                        'craft:tailor',
                        'craft:tiler',
                        'craft:tinsmith',
                        'craft:toolmaker',
                        'craft:turner',
                        'craft:upholsterer',
                        'craft:watchmaker',
                        'craft:water_well_drilling',
                        'craft:window_construction',
                    ],
                },
        },
        'building': {
            'residential': [
                'tourism:apartment',
                'building:hut',
                'building:shed',
                'building:tent',
                'building:apartments',
                'building:bungalow',
                'building:cabin',
                'building:detached',
                'building:dormitory',
                'building:ger', # A ger or yurt is a portable, round tent used as a temporary or permanent dwelling.
                'building:house',
                'building:houseboat',
                'building:residential',
                'building:semidetached_house',
                'building:static_caravan',
                
            ],
            'services': [
                'building:service',
                'building:transformer_tower',
                'building:water_tower',
                'building:toilets',
                'building:office',
                
            ],
            'commercial': [
                'building:commercial',
                'building:industrial',
                'building:kiosk',
            ],
            'other': [
                'building:warehouse',
                'building:hangar',
                'building:military',
                'building:bunker',
                'building:gatehouse',
                'building:roof',
                'building:ruins',
                'building:yes',
                'building:tree_house',
                'building:conservatory',
                'building:barn',
                'building:cowshed',
                'building:bakehouse',
                'building:farm_auxiliary',
                'building:greenhouse',
                'building:slurry_tank',
                'building:stable',
                'building:sty', # building for raising domestic pigs
                'building:container',
                'building:farm',
                'building:terrace',
                'building:digester', # building specially designed and constructed as a digester, a bioreactor for the production of inflatable biogas from biomass.
            ],
        },
        'civic': {
            'other': [
                'building:public',
                'building:civic',
                'amenity:community_centre',
            ],
            'government': [
                'building:government',
                'amenity:public_building',
                'amenity:townhall',
                'amenity:embassy',
            ],
            'library': [
                'amenity:library',
            ],
            'post_office': [
                'amenity:post_office',
            ],
            'fire': [
                'building:fire_station',
                'amenity:fire_station',
            ],
            'police': [
                'amenity:police',
            ],
            'courthouse': [
                'amenity:courthouse',
            ],
        },
        'leisure': [
            'amenity:casino',
            'amenity:internet_cafe',
            'amenity:theatre',
            'amenity:nightclub',
            'amenity:cinema',
            'amenity:arts_centre',
            'leisure:adult_gaming_centre',
            'leisure:amusement_arcade',
            'leisure:beach_resort',
            'leisure:bandstand',
            'leisure:bird_hide',
            'leisure:common',
            'leisure:dance',
            'leisure:disc_golf_course',
            'leisure:escape_game',
            'leisure:firepit',
            'leisure:fishing',
            'leisure:fitness_centre',
            'leisure:fitness_station',
            'leisure:hackerspace',
            'leisure:horse_riding',
            'leisure:ice_rink',
            'leisure:marina',
            'leisure:miniature_golf',
            'leisure:nature_reserve',
            'leisure:pitch',
            'leisure:playground',
            'leisure:slipway',
            'leisure:summer_camp',
            'leisure:swimming_area',
            'leisure:swimming_pool',
            'leisure:track',
            'leisure:water_park',
            'tourism:aquarium',
            'tourism:artwork',
            'tourism:attraction',
            'tourism:camp_pitch',
            'tourism:camp_site',
            'tourism:gallery',
            'tourism:museum',
            'tourism:picnic_site',
            'tourism:theme_park',
            'tourism:viewpoint',
            'tourism:zoo',
        ],
        'tourism': [
            'building:hotel',
            'tourism:alpine_hut',
            'tourism:chalet',
            'tourism:caravan_site',
            'tourism:guest_house',
            'tourism:hostel',
            'tourism:hotel',
            'tourism:information',
            'tourism:motel',
            'tourism:wilderness_hut',
            'tourism:yes',
            'amenity:love_hotel',
        ],
        'construction': [
            'building:construction',
        ],
    },
    'landuse': {
        'residential': [
            'landuse:residential',
        ], 
        'industrial': [
            'landuse:industrial',
        ],
        'commercial': [
            'landuse:commercial',
            'landuse:retail',
        ],
        'construction': [
            'landuse:construction',
        ],
        'construction': [
            'landuse:construction',
        ],
        'religious': [
            'landuse:religious',
        ],
        'greenery': [
            'landuse:farmland',
            'landuse:grass',
            'landuse:forest',
            'landuse:meadow',
            'landuse:orchard',
            'landuse:farmyard',
            'landuse:vineyard',
            'landuse:allotments',
            'landuse:village_green',
            'landuse:greenhouse_horticulture',
            'landuse:brownfield',
            'landuse:logging',
            'landuse:greenfield',
            'landuse:vineyard',
            'landuse:vineyard',            
        ],
        'other':[
            'landuse:cemetery',  
            'landuse:recreation_ground',  
            'landuse:garages',  
            'landuse:military',  
        ],
        'water':[
            'landuse:reservoir',
            'landuse:basin',
        ],
    },
    'circulation_spaces': {
        'cycleways': [
            'cycleway:lane',
            'cycleway:opposite',
            'cycleway:opposite_lane',
            'cycleway:track',
            'cycleway:opposite_track',
            'cycleway:right:lane',
            
        ],
        'cycleways_sharedbus': [
            'cycleway:share_busway',
            'cycleway:opposite_share_busway',
        ],
        'cycleways_sharedlane': [
            'cycleway:shared_lane',
        ],
        'footways': [
            'footway:sidewalk',
            'highway:pedestrian',
            'highway:track',
            'highway:steps',
            'highway:corridor',
            'highway:path',
            'highway:footway',
            'highway:bridleway',
            'highway:elevator',
        ],
        'footways_crossing': [
            'footway:crossing',
            'highway:crossing',
        ],
        'roads':{
            'motorway': [
                'highway:motorway_junction',
                'highway:motorway',
                'highway:trunk',
                'highway:motorway_link',
                'highway:trunk_link',
                'highway:emergency_bay',
                'highway:toll_gantry',
                'highway:service',
                'highway:services',
                'highway:rest_area',
            ],
            'primary': [
                'highway:primary',
                'highway:primary_link',
            ],
            'secondary': [
                'highway:secondary',
                'highway:secondary_link',
            ],
            'tertiary': [
                'highway:tertiary',
                'highway:tertiary_link',
            ],
            'street': [
                'highway:mini_roundabout',
                'highway:residential',
                'highway:living_street',
                'highway:turning_circle',
                'highway:turning_loop',
                'highway:road',
            ],
            'other': [
                'highway:passing_place',
                'highway:unclassified',
                'highway:raceway',
                'highway:escape',
            ],
            'bridge': [
                'building:bridge',
            ],
        },
        'public_transportation': [
            'public_transportation:stop_position',
            'public_transportation:platform',
            'public_transportation:station',
            'highway:bus_guideway',
            'highway:busway',
            'highway:platform',
        ],
        'rail': [
            'railway:abandoned',
            'railway:construction',
            'railway:disused',
            'railway:funicular',
            'railway:light_rail',
            'railway:miniature',
            'railway:monorail',
            'railway:narrow_gauge',
            'railway:preserved',
            'railway:rail',
            'railway:tram',
            'railway:halt',
            'railway:stop_position',
            'railway:switch',
            'railway:buffer_stop',
            'railway:derail',
            'railway:crossing',
            'railway:level_crossing',
            'railway:railway_crossing',
            'railway:turntable',
            'railway:roundhouse',
            'railway:traverser',
            'railway:wash',
            'railway:user defined',
        ],
        'rail_subway': [
            'railway:subway',
        ],
    },
    'habitat': {
        'nature': [
            'natural:wood',
            'natural:scrub',
            'natural:heath',
            'natural:moor',
            'natural:grassland',
            'natural:fell',
            'natural:bare_rock',
            'natural:scree',
            'natural:shingle',
            'natural:sand',
            'natural:mud',
        ],
    },
    'barrier': {
        'linear': [
            'barrier:cable_barrier',
            'barrier:city_wall',
            'barrier:fence',
            'barrier:guard_rail',
            'barrier:handrail',
            'barrier:retaining_wall',
            'barrier:wall',
            'barrier:block',
            'barrier:bollard',
            'barrier:debris',
            'barrier:ditch',
            'barrier:chain',
            'barrier:log',
            'barrier:kerb',
            'barrier:jersey_barrier',
            'barrier:rope',
            'barrier:yes',
        ],
        'access': [
            'barrier:lift_gate',
            'barrier:swing_gate',
            'barrier:turnstile',
            'barrier:toll_booth',
            'barrier:border_control',
            'barrier:bump_gate',
            'barrier:bus_trap',
            'barrier:cattle_grid',
            'barrier:cycle_barrier',
            'barrier:entrance',
            'barrier:full',
            'barrier:gate',
            'barrier:hampshire_gate',
            'barrier:height_restrictor',
            'barrier:horse_stile',
            'barrier:kissing_gate',
            'barrier:motorcycle_barrier',
            'barrier:sally_port',
            'barrier:stile',
            'barrier:sump_buster',
            'barrier:spikes',
        ],
    },
    'furniture': {
        'plants': [
            'barrier:hedge',
            'natural:tree_row',
            'natural:tree',
        ],
        'park': [
            'leisure:dog_park',
            'leisure:garden',
            'leisure:park',
            'leisure:picnic_table',
        ],
        'signaling': [
            'highway:milestone',
            'highway:traffic_signals',
            'highway:stop',
            'highway:traffic_mirror',
            'highway:trailhead',
            'highway:give_way',
            'highway:emergency_access_point',
            'railway:signal',
        ],
        'illumination': [
            'highway:street_lamp',
        ],
        'street': [
            'amenity:vending_machine',
            'amenity:recycling',
            'amenity:waste_basket',
            'amenity:toilets',
            'amenity:water_point',
            'amenity:watering_place',
            'amenity:bbq',
            'amenity:bench',
            'amenity:dog_toilet',
            'amenity:drinking_water',
            'amenity:fountain',
            'amenity:post_box',
            'amenity:telephone',
            'amenity:bicycle_repair_station',
            'amenity:grit_bin',
            'amenity:clock',
        ],
    },
    'transportation': {
        'public_transportation': [
            'building:train_station',
            'amenity:bus_station',
            'building:transportation',
            'highway:bus_stop',
            'railway:platform',
            'railway:station',
            'railway:subway_entrance',
            'railway:tram_stop',
        ],
        'parking': [
            'amenity:motorcycle_parking',
            'amenity:parking',
            'amenity:parking_entrance',
            'amenity:parking_space',
            'building:parking',
            'amenity:bicycle_parking',
        ],
        'charging_station': [
            'amenity:charging_station',
        ],
        'speed_camera': [
            'highway:speed_camera',
        ],
        'car_sharing': [
            'amenity:car_sharing',
        ],
        'taxi': [
            'amenity:taxi',
        ],
        'garage': [
            'building:garage',
            'building:garages',
            'building:carport',
        ],
        'fuel': [
            'amenity:fuel',
        ],
    }
}
